// Service worker: after one visit the game starts without a network.
//
// A classic worker, not a module, because iPadOS only learned module workers
// late and this has to run on the device the game is aimed at.
//
// The block below is written by `npm run precache`. Do not edit it by hand; a
// unit test compares it against the files in the repository and fails when the
// two have drifted apart, which is what makes an update actually arrive.

// --- generated by npm run precache, do not edit ---
const VERSION = '0.7.0';
const BUILD = '70d244881a3e';
const PRECACHE = [
  './assets/fonts/bangers-latin-400-normal.woff2',
  './assets/fonts/barlow-condensed-latin-500-normal.woff2',
  './assets/fonts/barlow-condensed-latin-700-normal.woff2',
  './assets/fonts/pirata-one-latin-400-normal.woff2',
  './assets/icons/apple-touch-icon.png',
  './assets/icons/icon-192.png',
  './assets/icons/icon-512.png',
  './assets/icons/icon-maskable-192.png',
  './assets/icons/icon-maskable-512.png',
  './index.html',
  './manifest.webmanifest',
  './src/audio/index.js',
  './src/audio/synth.js',
  './src/core/loop.js',
  './src/core/phases.js',
  './src/core/prefs.js',
  './src/core/random.js',
  './src/core/seed.js',
  './src/core/state.js',
  './src/core/updates.js',
  './src/data/audio.js',
  './src/data/combat.js',
  './src/data/commands.js',
  './src/data/doctrines.js',
  './src/data/economy.js',
  './src/data/enemies.js',
  './src/data/map.js',
  './src/data/pods.js',
  './src/data/ranks.js',
  './src/data/recipes.js',
  './src/data/rules.js',
  './src/data/settings.js',
  './src/data/specials.js',
  './src/data/strings.js',
  './src/data/supply.js',
  './src/data/version.js',
  './src/data/waves.js',
  './src/input/gestures.js',
  './src/input/guards.js',
  './src/input/keyboard.js',
  './src/input/pointer.js',
  './src/main.js',
  './src/render/atmosphere.js',
  './src/render/backdrop.js',
  './src/render/camera.js',
  './src/render/canvas.js',
  './src/render/draw.js',
  './src/render/effects.js',
  './src/render/enemySprites.js',
  './src/render/ground.js',
  './src/render/iso.js',
  './src/render/objects.js',
  './src/render/palette.js',
  './src/render/pods.js',
  './src/render/scene.js',
  './src/render/sprites/compose.js',
  './src/render/sprites/enemies.js',
  './src/render/sprites/manifest.js',
  './src/render/sprites/pods.js',
  './src/render/sprites/rasterizer.js',
  './src/render/sprites/towers.js',
  './src/render/towerFx.js',
  './src/render/towerSprites.js',
  './src/sim/abilities.js',
  './src/sim/actions.js',
  './src/sim/combat.js',
  './src/sim/commands.js',
  './src/sim/damage.js',
  './src/sim/debug.js',
  './src/sim/economy.js',
  './src/sim/effects.js',
  './src/sim/enemies.js',
  './src/sim/grid.js',
  './src/sim/koloss.js',
  './src/sim/mapgen.js',
  './src/sim/pathfinding.js',
  './src/sim/pods.js',
  './src/sim/projectiles.js',
  './src/sim/route.js',
  './src/sim/rubble.js',
  './src/sim/score.js',
  './src/sim/selection.js',
  './src/sim/step.js',
  './src/sim/targeting.js',
  './src/sim/towers.js',
  './src/sim/waves.js',
  './src/sim/zones.js',
  './src/storage/index.js',
  './src/storage/profile.js',
  './src/ui/badges.js',
  './src/ui/codex.js',
  './src/ui/commands.js',
  './src/ui/controls.js',
  './src/ui/debug.js',
  './src/ui/hud.js',
  './src/ui/icons.js',
  './src/ui/info.js',
  './src/ui/loading.js',
  './src/ui/menu.js',
  './src/ui/records.js',
  './src/ui/runeButton.js',
  './src/ui/selection.js',
  './src/ui/style.css',
];
// --- end generated ---

/**
 * One cache per build. The hash covers the contents of every precached file, so
 * any change gives the new worker a cache of its own and the old one is thrown
 * away on activate. Nothing is ever served from a previous build's cache.
 */
const CACHE = `nachschubfront-${VERSION}-${BUILD}`;

self.addEventListener('install', (event) => {
  // No skipWaiting: a running match must not be pulled out from under the
  // player. The new worker waits until the page asks for it (see 'message').
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      for (const name of await caches.keys()) {
        if (name !== CACHE && name.startsWith('nachschubfront-')) await caches.delete(name);
      }
      await self.clients.claim();
    })(),
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // Any navigation lands on the one page the game has. That also covers a deep
  // link with a seed in the query, which is not a cache entry of its own.
  if (request.mode === 'navigate') {
    event.respondWith(
      (async () => {
        const cached = await caches.match('./index.html', { cacheName: CACHE });
        if (cached) return cached;
        return fetch(request);
      })(),
    );
    return;
  }

  event.respondWith(
    (async () => {
      const cached = await caches.match(request, { cacheName: CACHE, ignoreSearch: true });
      if (cached) return cached;
      // Not in the build: fetch it and keep it, so a file added later is
      // available offline from its second use on.
      try {
        const response = await fetch(request);
        if (response.ok && response.type === 'basic') {
          const cache = await caches.open(CACHE);
          cache.put(request, response.clone());
        }
        return response;
      } catch (error) {
        // Offline and nothing cached: let the page deal with it.
        throw error;
      }
    })(),
  );
});

self.addEventListener('message', (event) => {
  // The page asks for the update once the player has said yes to it.
  if (event.data && event.data.type === 'skipWaiting') self.skipWaiting();
});
