// Writes the 50-wave table in src/data/waves.js from the rules in
// wave-rules.mjs. Run with `npm run waves`.
//
// The table is written out in full instead of being computed at runtime, so it
// stays readable and can be tuned wave by wave in M6. Hand edits are lost on
// the next run: change the rules in wave-rules.mjs, not the output.
//
// Since M6 the rules are a module of their own, because the balancing tools
// have to reach them too (`npm run replay -- --data`).

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { WAVE_RULES, buildWaves } from './wave-rules.mjs';

const OUT = fileURLToPath(new URL('../../src/data/waves.js', import.meta.url));

/** Writes the table as a readable source file. Exported for the guarding test. */
export function waveTableSource(rules = WAVE_RULES) {
  const waves = buildWaves(rules);
  const lines = waves.map((w, i) => {
    const groups = w.groups
      .map((g) => `    { type: '${g.type}', count: ${g.count}, interval: ${g.interval}, delay: ${g.delay} },`)
      .join('\n');
    const total = w.groups.reduce((sum, g) => sum + g.count, 0);
    return `  // Wave ${i + 1} · ${w.kind} · ${total} enemies\n  { kind: '${w.kind}', scale: ${w.scale}, groups: [\n${groups}\n  ] },`;
  });

  return `// The complete wave list (GDD section 9, "Wellenaufbau" and "Einstieg").
//
// Generated by tests/tools/make-waves.mjs (\`npm run waves\`) from the rules in
// tests/tools/wave-rules.mjs: five-wave cycle horde, armour, air, warp, mixed,
// every tenth wave a boss with escort. The first ${rules.earlyWaves} waves carry ${Math.round((1 - rules.earlyFactor) * 100)} percent fewer
// enemies, and a cycle slot whose lead enemy is not unlocked yet is called what
// is left of it.
// \`scale\` multiplies the health and shield of every enemy of that wave
// (${rules.healthGrowth} to the power of wave minus one). Each group spawns \`count\`
// enemies of \`type\`, \`interval\` seconds apart, starting \`delay\` seconds after
// the wave begins. Edits here are overwritten on the next run of the tool.

export const WAVES = [
${lines.join('\n')}
];

/** Health factor of a wave; 1 for anything outside the table. */
export function waveScale(wave) {
  return WAVES[wave - 1]?.scale ?? 1;
}
`;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const source = waveTableSource();
  writeFileSync(OUT, source);
  console.log(`${WAVE_RULES.waveCount} waves written to src/data/waves.js`);
}
